import type { Metadata } from "next";
import "./globals.css";
import { inter, noto, barlow } from "./fonts";
import ClientLayout from "@/components/Global/ClientLayout";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${inter.variable} ${noto.variable} ${barlow.variable}`}
    >
      <body className="font-sans">
        <div className="bg-[url(/assets/background.jpg)] bg-cover bg-center h-screen fixed w-full z-[-3]"></div>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
